# Generated by Django 5.0.6 on 2024-07-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionappart',
            name='region',
            field=models.CharField(default='Default Region', max_length=100),
        ),
    ]
