# Generated by Django 5.0.6 on 2024-07-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0005_remove_predictionmaison_ascenseur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeurFonciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=100)),
                ('type_local', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('valeur_fonciere', models.FloatField()),
            ],
        ),
    ]
