# Generated by Django 5.0.6 on 2024-07-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0006_valeurfonciere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valeurfonciere',
            old_name='departement',
            new_name='dep_name',
        ),
    ]
