# Generated by Django 5.0.6 on 2024-07-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0007_rename_departement_valeurfonciere_dep_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valeurfonciere',
            old_name='dep_name',
            new_name='departement',
        ),
    ]
