# Generated by Django 5.0.6 on 2024-07-14 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0008_rename_dep_name_valeurfonciere_departement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValeurFonciere',
        ),
        migrations.RemoveField(
            model_name='predictionappart',
            name='adresse_postale',
        ),
        migrations.RemoveField(
            model_name='predictionmaison',
            name='adresse_postale',
        ),
        migrations.AddField(
            model_name='predictionappart',
            name='adresse_code_voie',
            field=models.CharField(choices=[('', '---'), ('ALL', 'Allée'), ('AV', 'Avenue'), ('BD', 'Boulevard'), ('CHE', 'Chemin'), ('RUE', 'Rue'), ('IMP', 'Impasse'), ('QUAI', 'Quai'), ('PL', 'Place'), ('CRS', 'Cours'), ('RES', 'Résidence'), ('FG', 'Faubourg'), ('VOIE', 'Voie'), ('PTR', 'Porte'), ('PAS', 'Passage'), ('MAIL', 'Mail'), ('SEN', 'Sentier'), ('PTE', 'Petite Rue'), ('TRT', 'Traversée'), ('ZAC', "Zone d'Activité Commerciale"), ('ZI', 'Zone Industrielle')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionappart',
            name='adresse_nom_voie',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionappart',
            name='adresse_numero',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='predictionappart',
            name='adresse_suffixe',
            field=models.CharField(blank=True, choices=[('', '---'), ('T', 'Ter'), ('A', 'A'), ('B', 'Bis'), ('D', 'D'), ('G', 'G'), ('C', 'C'), ('F', 'F'), ('Q', 'Quater')], default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='predictionmaison',
            name='adresse_code_voie',
            field=models.CharField(choices=[('', '---'), ('ALL', 'Allée'), ('AV', 'Avenue'), ('BD', 'Boulevard'), ('CHE', 'Chemin'), ('RUE', 'Rue'), ('IMP', 'Impasse'), ('QUAI', 'Quai'), ('PL', 'Place'), ('CRS', 'Cours'), ('RES', 'Résidence'), ('FG', 'Faubourg'), ('VOIE', 'Voie'), ('PTR', 'Porte'), ('PAS', 'Passage'), ('MAIL', 'Mail'), ('SEN', 'Sentier'), ('PTE', 'Petite Rue'), ('TRT', 'Traversée'), ('ZAC', "Zone d'Activité Commerciale"), ('ZI', 'Zone Industrielle')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionmaison',
            name='adresse_nom_voie',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionmaison',
            name='adresse_numero',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='predictionmaison',
            name='adresse_suffixe',
            field=models.CharField(blank=True, choices=[('', '---'), ('T', 'Ter'), ('A', 'A'), ('B', 'Bis'), ('D', 'D'), ('G', 'G'), ('C', 'C'), ('F', 'F'), ('Q', 'Quater')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='predictionappart',
            name='date_predicted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='predictionappart',
            name='region',
            field=models.CharField(choices=[('', '---'), ('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes'), ('Bourgogne-Franche-Comté', 'Bourgogne-Franche-Comté'), ('Bretagne', 'Bretagne'), ('Centre-Val de Loire', 'Centre-Val de Loire'), ('Corse', 'Corse'), ('Grand Est', 'Grand Est'), ('Hauts-de-France', 'Hauts-de-France'), ('Île-de-France', 'Île-de-France'), ('Normandie', 'Normandie'), ('Nouvelle-Aquitaine', 'Nouvelle-Aquitaine'), ('Occitanie', 'Occitanie'), ('Pays de la Loire', 'Pays de la Loire'), ("Provence-Alpes-Côte d'Azur", "Provence-Alpes-Côte d'Azur")], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionmaison',
            name='date_predicted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='predictionmaison',
            name='region',
            field=models.CharField(choices=[('', '---'), ('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes'), ('Bourgogne-Franche-Comté', 'Bourgogne-Franche-Comté'), ('Bretagne', 'Bretagne'), ('Centre-Val de Loire', 'Centre-Val de Loire'), ('Corse', 'Corse'), ('Grand Est', 'Grand Est'), ('Hauts-de-France', 'Hauts-de-France'), ('Île-de-France', 'Île-de-France'), ('Normandie', 'Normandie'), ('Nouvelle-Aquitaine', 'Nouvelle-Aquitaine'), ('Occitanie', 'Occitanie'), ('Pays de la Loire', 'Pays de la Loire'), ("Provence-Alpes-Côte d'Azur", "Provence-Alpes-Côte d'Azur")], default='', max_length=100),
        ),
    ]
